### ISSUE TITLE
curses.h: No such file or directory

### ISSUE THREAD

**Issue by rafaelquint** [adk3798/angrybull#1]
Recieving this issue once I input the "make" command
![Screenshot from 2019-08-07 15-20-08](https://user-images.githubusercontent.com/36835422/62651399-e1d15900-b926-11e9-87fd-beb3961f2fca.png)

**Comment by adk3798** [comment]
Try this command before make:

sudo dnf install ncurses-devel ncurses

**Comment by rafaelquint** [comment]
It worked -- Thanks!
